### ISSUE TITLE
Make some releases!

### ISSUE THREAD

**Issue by traverseda** [verse/verse#32]
https://help.github.com/articles/creating-releases

Some releases (make sure it builds and all that) would be good. Just so anyone collaborating has a stable target to test their code against.

**Comment by traverseda** [comment]
That milestone looks like it's still a pretty long way away. Maybe do a version 0.0.1 now, so I have a reference version when I'm trying to rope other programmers in?

Also, verse-entities.

**Comment by jirihnidek** [comment]
Version 0.0.1 sounds reasonable. I will make some releases tomorrow.

**Comment by traverseda** [comment]
Thanks. Should be easier to make people work on things if we have a common version.

**Comment by jirihnidek** [comment]
Created version 0.0.1:

https://github.com/verse/verse/releases/tag/v0.0.1

**Comment by jirihnidek** [comment]
Verse entities has version too:

https://github.com/verse/verse-entities/releases/tag/v0.0.1

**Comment by traverseda** [comment]
Awesome, thanks. I'm going to close this since it's already part of the v0.1 milestone.
